import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import TrevelPerfection from "@/components/TrevelPerfection";
import Location from "@/components/Location";
import Tour from "@/components/Tour";
import About from "@/components/About";
import Contact from "@/components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>TripGoal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <TrevelPerfection />
        <Location />
        <Tour />
        <About />
        <Contact />
      </>
    </>
  );
}
